version: '3.8'

services:
  web:
    build: './project/data-ingest'
    command: 'uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 5010'
    volumes:
      - ./project/data-ingest:/usr/src/app
    ports:
      - 5010:5010
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    