version: '3.8'

services:

  data-ingest:
    build: 
      context: ./data-ingest
      dockerfile: docker/Dockerfile

    volumes:
      - ./data-ingest/shared:/usr/src/app/shared
    ports:
      - 5010:5010
    env_file: 
      - ./.env
  
  db-ingest:
    build: 
      context: ./data-ingest
      dockerfile: docker/Dockerfile.db_ingest

    volumes:
      - ./data-ingest/shared:/usr/src/home/shared
    env_file:
      - ./.env
    depends_on:
      - server-db
  
  server-db:
    build: 
      context: ./data-ingest/docker/db
      dockerfile: Dockerfile
    expose:  
      - 5432
    env_file:
      - ./.env

    