version: '3.8'

services:
  web:
    build: './project/data-ingest'
    volumes:
      - ./project/data-ingest/:/usr/src/app
    ports:
      - 5010:5010
    env_file: 
      - ./project/data-ingest/.env
    