version: '3.8'

services:
  web:
    build: './project/data-ingest'
    volumes:
      - ./project/data-ingest/:/usr/src/app
    ports:
      - 5010:5010
    env_file: 
      - ./.env
    depends_on:
      - web-db
  
  web-db:
    build: './project/db'
    expose:  
      - 5432
    env_file:
      - ./.env

    